spring:
  application:
    name: JavaWeb08_RequestAndResponse

  datasource:
    url: jdbc:mysql://localhost:3306/db01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  servlet:
    multipart:
      # 配置单个文件最大上传大小（默认1MB）
      max-file-size: 10MB
      # 配置单个请求最大上传大小（一次请求可以上传多个文件）
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

