spring:
  application:
    name: JavaWeb08_RequestAndResponse

  datasource:
    url: jdbc:mysql://localhost:3306/db01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

