spring:
  application:
    name: JavaWeb13MyBatisPlus

  datasource:
    url: jdbc:mysql://localhost:3306/web_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8080

mybatis-plus:
  # 指定 Mapper XML 文件路径（若使用 XML）
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类别名扫描包（简化 XML文件 中 resultType 书写）
  type-aliases-package: com.wzb.pojo
  configuration:
    # 开启下划线转驼峰命名法
    map-underscore-to-camel-case: true
    # 显示 SQL 日志（调试用）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 指定默认使用的Enum处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  # 全局配置
  global-config:
    # 删除策略配置
    db-config:
      # 使用逻辑删除
      logic-delete-field: deleted




