spring:
  application:
    name: JavaWeb13MyBatisPlus

  datasource:
    url: jdbc:mysql://localhost:3306/web_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8081

mybatis-plus:
  configuration:
    # 开启驼峰命名映射（数据库字段 user_name → 实体类属性 userName）
    map-underscore-to-camel-case: true
    # 显示 SQL 日志（调试用）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定 Mapper XML 文件路径（若使用 XML）
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类别名扫描包（简化 XML 中 resultType 书写）
  type-aliases-package: com.wzb.pojo



