spring:
  application:
    name: JavaWeb13MyBatisPlus

  datasource:
    url: jdbc:mysql://localhost:3306/web_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 显示 SQL 日志（调试用）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  # 指定 Mapper XML 文件路径（若使用 XML）
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类别名扫描包（简化 XML 中 resultType 书写）
  type-aliases-package: com.wzb.pojo
  global-config:
    db-config:
      logic-delete-field: deleted




