spring:
  application:
    name: JavaWeb06_Develop

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true


user:
  name: zhangsan
  age: 18
  password: 123456

hobby:
  - java
  - game
  - sport
  - sleep
